"""The e2e workflow, generated from .projenrc.ts.

A GitHub expression inside a `run:` block is pasted into the script before the shell sees it, so a value
that is not what the author expected becomes code. The e2e job therefore reads ENV and the Regions from
the environment, and takes every other value through a step's `env:`.
"""

import re
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parent.parent
E2E = REPO / ".github" / "workflows" / "e2e.yml"

JOB_VARIABLES = ("ENV", "AWS_REGION", "STANDBY_REGION")


def workflow():
    return yaml.safe_load(E2E.read_text())


def job():
    return next(iter(workflow()["jobs"].values()))


def steps():
    return job()["steps"]


def step(name):
    (found,) = [s for s in steps() if s.get("name") == name]
    return found


class TestNoExpressionsInRunBlocks:

    def test_no_run_block_contains_a_github_expression(self):
        offenders = [s["name"] for s in steps() if "${{" in s.get("run", "")]
        assert offenders == [], f"use the job's environment variables in: {offenders}"

    def test_the_file_was_regenerated_from_projen_not_edited_by_hand(self):
        assert E2E.read_text().startswith("# ~~ Generated by projen")


class TestVariablesTheRunBlocksRead:

    def _reads(self, name):
        return {v for v in JOB_VARIABLES if re.search(rf"\$\{{?{v}\b", name)}

    @pytest.mark.parametrize("variable", JOB_VARIABLES)
    def test_each_variable_is_set_before_the_first_step_that_reads_it(self, variable):
        all_steps = steps()
        readers = [i for i, s in enumerate(all_steps) if variable in self._reads(s.get("run", ""))]
        assert readers, f"no run block reads {variable}: is the test out of date?"
        if variable in job().get("env", {}):
            return
        # ENV is appended to $GITHUB_ENV by an early step, which exports it to every step after it.
        setters = [i for i, s in enumerate(all_steps) if re.search(rf"{variable}=.*>>\s*\"?\$GITHUB_ENV", s.get("run", ""))]
        assert setters, f"{variable} is neither in the job's env nor written to $GITHUB_ENV"
        assert min(setters) < min(readers), f"{variable} is read before it is set"
