management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: ${port:8080}

logging:
  level:
    root: info

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration
